# IMPORTING THE REQUIRED LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# READING THE DATASET

In [ ]:
df = pd.read_csv("breast-cancer.csv")

# CHECKING THE SIZE OF THE DATA

In [ ]:
df.shape

(569, 32)

# CHECKING THE DATA TYPE OF EACH COLUMN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
df['diagnosis'] = df['diagnosis'].replace({'M':1,'B':0})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    int64  
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

# DESCRIBING THE DATASET

In [ ]:
df.describe()

id   diagnosis  radius_mean  texture_mean  perimeter_mean  \
count  5.690000e+02  569.000000   569.000000    569.000000      569.000000   
mean   3.037183e+07    0.372583    14.127292     19.289649       91.969033   
std    1.250206e+08    0.483918     3.524049      4.301036       24.298981   
min    8.670000e+03    0.000000     6.981000      9.710000       43.790000   
25%    8.692180e+05    0.000000    11.700000     16.170000       75.170000   
50%    9.060240e+05    0.000000    13.370000     18.840000       86.240000   
75%    8.813129e+06    1.000000    15.780000     21.800000      104.100000   
max    9.113205e+08    1.000000    28.110000     39.280000      188.500000   

         area_mean  smoothness_mean  compactness_mean  concavity_mean  \
count   569.000000       569.000000        569.000000      569.000000   
mean    654.889104         0.096360          0.104341        0.088799   
std     351.914129         0.014064          0.052813        0.079720   
min     143.500000         0.052630          0.019380        0.000000   
25%     420.300000         0.086370          0.064920        0.029560   
50%     551.100000         0.095870          0.092630        0.061540   
75%     782.700000         0.105300          0.130400        0.130700   
max    2501.000000         0.163400          0.345400        0.426800   

       concave points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count           569.000000  ...    569.000000     569.000000       569.000000   
mean              0.048919  ...     16.269190      25.677223       107.261213   
std               0.038803  ...      4.833242       6.146258        33.602542   
min               0.000000  ...      7.930000      12.020000        50.410000   
25%               0.020310  ...     13.010000      21.080000        84.110000   
50%               0.033500  ...     14.970000      25.410000        97.660000   
75%               0.074000  ...     18.790000      29.720000       125.400000   
max               0.201200  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 32 columns]

# CHECKING THE NULL VALUES

In [ ]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

# PRINTING COLUMN NAMES

In [ ]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

# CORRELATIONS

In [ ]:
for i in df.columns:
    print(i,"------>",df[i].corr(df['diagnosis']))

diagnosis ------> 1.0
radius_mean ------> 0.7300285113754558
perimeter_mean ------> 0.742635529725832
area_mean ------> 0.7089838365853891
compactness_mean ------> 0.5965336775082525
concavity_mean ------> 0.6963597071719048
concave points_mean ------> 0.7766138400204349
radius_se ------> 0.5671338208247165
perimeter_se ------> 0.5561407034314825
area_se ------> 0.5482359402780237
radius_worst ------> 0.7764537785950386
perimeter_worst ------> 0.7829141371737584
area_worst ------> 0.7338250349210504
compactness_worst ------> 0.5909982378417914
concavity_worst ------> 0.6596102103692325
concave points_worst ------> 0.7935660171412687


# REMOVING LOW CORRELATED COLUMNS 

In [ ]:
df.drop(['id','smoothness_mean','symmetry_mean','fractal_dimension_mean','texture_se','smoothness_se','compactness_se','concavity_se','symmetry_se','fractal_dimension_se','fractal_dimension_worst'],axis=1,inplace=True)

In [ ]:
df.drop(['concave points_se','symmetry_worst','smoothness_worst','texture_worst','texture_mean'],axis=1,inplace=True)

In [ ]:
len(df.columns)

16

In [ ]:
df.columns

Index(['diagnosis', 'radius_mean', 'perimeter_mean', 'area_mean',
       'compactness_mean', 'concavity_mean', 'concave points_mean',
       'radius_se', 'perimeter_se', 'area_se', 'radius_worst',
       'perimeter_worst', 'area_worst', 'compactness_worst', 'concavity_worst',
       'concave points_worst'],
      dtype='object')

In [ ]:
df.tail()

diagnosis  radius_mean  perimeter_mean  area_mean  compactness_mean  \
564          1        21.56          142.00     1479.0           0.11590   
565          1        20.13          131.20     1261.0           0.10340   
566          1        16.60          108.30      858.1           0.10230   
567          1        20.60          140.10     1265.0           0.27700   
568          0         7.76           47.92      181.0           0.04362   

     concavity_mean  concave points_mean  radius_se  perimeter_se  area_se  \
564         0.24390              0.13890     1.1760         7.673   158.70   
565         0.14400              0.09791     0.7655         5.203    99.04   
566         0.09251              0.05302     0.4564         3.425    48.55   
567         0.35140              0.15200     0.7260         5.772    86.22   
568         0.00000              0.00000     0.3857         2.548    19.15   

     radius_worst  perimeter_worst  area_worst  compactness_worst  \
564        25.450           166.10      2027.0            0.21130   
565        23.690           155.00      1731.0            0.19220   
566        18.980           126.70      1124.0            0.30940   
567        25.740           184.60      1821.0            0.86810   
568         9.456            59.16       268.6            0.06444   

     concavity_worst  concave points_worst  
564           0.4107                0.2216  
565           0.3215                0.1628  
566           0.3403                0.1418  
567           0.9387                0.2650  
568           0.0000                0.0000

# IMPORTING REQUIRED MODELS AND METRICS

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Train Test Split
from sklearn.model_selection import train_test_split

# Metrics
from sklearn.metrics import confusion_matrix, accuracy_score

# Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# DIVIDING THE DEPENDENT AND INDEPENDENT VARIABLES

In [ ]:
y = df['diagnosis']
X = df.drop(['diagnosis'],axis = 1)

# DIVIDING THE DATA INTO TRAIN AND TEST

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
lst = [x_train,x_test,y_train,y_test]
for data in lst:
  print("shape","---->",data.shape)

shape ----> (455, 15)
shape ----> (114, 15)
shape ----> (455,)
shape ----> (114,)


# MAKING PIPELINE FOR EVERY MODEL

In [ ]:
mdl_1 = make_pipeline(StandardScaler(), KNeighborsClassifier()) 
mdl_2 = make_pipeline(StandardScaler(), LogisticRegression()) 
mdl_3 = make_pipeline(StandardScaler(), SVC()) 
mdl_4 = make_pipeline(StandardScaler(), DecisionTreeClassifier()) 
mdl_5 = make_pipeline(StandardScaler(), RandomForestClassifier())

# FITTING AND PREDICTING ACCURACY OF MODELS

In [ ]:
mdl_lst = [mdl_1,mdl_2,mdl_3,mdl_4,mdl_5]
accuracy_lst = []
for mdl in mdl_lst:
  i = 1
  mdl.fit(x_train,y_train)
  y_pred = mdl.predict(x_test)
  print("")
  print("******CLASSIFICATION MODEL******")
  i = i+1
  print("")
  print("CONFUSION MATRIX")
  print(confusion_matrix(y_test,y_pred))
  print("")
  print("ACCURACY SCORE")
  print(accuracy_score(y_test,y_pred))
  print("----------------------------")
  accuracy_lst.append(accuracy_score(y_test,y_pred)) 
 


******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[70  1]
 [ 3 40]]

ACCURACY SCORE
0.9649122807017544
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[69  2]
 [ 2 41]]

ACCURACY SCORE
0.9649122807017544
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[70  1]
 [ 4 39]]

ACCURACY SCORE
0.956140350877193
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[68  3]
 [ 5 38]]

ACCURACY SCORE
0.9298245614035088
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[69  2]
 [ 3 40]]

ACCURACY SCORE
0.956140350877193
----------------------------


# CHECKING FOR HIGH ACCURACY SCORE AMOUNG THE MODELS

In [ ]:
print(accuracy_lst.index(max(accuracy_lst)))


0


# SAVING THE MODEL IN PICKLE FILE

In [ ]:
import pickle

In [ ]:
filename = 'breast_cancer.pkl'
pickle.dump(mdl_2, open(filename, 'wb'))