# IMPORTING THE REQUIRED LIBRARIES

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# READING THE DATASET

In [ ]:
df = pd.read_csv("cancer patient data sets.csv")
df.head()

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0      0         P1   33       1              2            4             5   
1      1        P10   17       1              3            1             5   
2      2       P100   35       1              4            5             6   
3      3      P1000   37       1              7            7             7   
4      4       P101   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                     4             3                     2  ...        3   
1                     3             4                     2  ...        1   
2                     5             5                     4  ...        8   
3                     7             6                     7  ...        4   
4                     7             7                     6  ...        3   

   Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0            4                    2         2                      3   
1            3                    7         8                      6   
2            7                    9         2                      1   
3            2                    3         1                      4   
4            2                    4         1                      4   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                         1              2          3        4     Low  
1                         2              1          7        2  Medium  
2                         4              6          7        2    High  
3                         5              6          7        5    High  
4                         2              4          2        3    High  

[5 rows x 26 columns]

# CHECKING THE SIZE OF THE DATA

In [ ]:
df.shape

(1000, 26)

# CHECKING THE DATA TYPE OF EACH COLUMN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   index                     1000 non-null   int64 
 1   Patient Id                1000 non-null   object
 2   Age                       1000 non-null   int64 
 3   Gender                    1000 non-null   int64 
 4   Air Pollution             1000 non-null   int64 
 5   Alcohol use               1000 non-null   int64 
 6   Dust Allergy              1000 non-null   int64 
 7   OccuPational Hazards      1000 non-null   int64 
 8   Genetic Risk              1000 non-null   int64 
 9   chronic Lung Disease      1000 non-null   int64 
 10  Balanced Diet             1000 non-null   int64 
 11  Obesity                   1000 non-null   int64 
 12  Smoking                   1000 non-null   int64 
 13  Passive Smoker            1000 non-null   int64 
 14  Chest Pain               

In [ ]:
df["Level"]=df["Level"].astype("category")
df["Level"]=df["Level"].cat.codes

# DESCRIBING THE DATASET

In [ ]:
df.describe()

index          Age       Gender  Air Pollution  Alcohol use  \
count  1000.000000  1000.000000  1000.000000      1000.0000  1000.000000   
mean    499.500000    37.174000     1.402000         3.8400     4.563000   
std     288.819436    12.005493     0.490547         2.0304     2.620477   
min       0.000000    14.000000     1.000000         1.0000     1.000000   
25%     249.750000    27.750000     1.000000         2.0000     2.000000   
50%     499.500000    36.000000     1.000000         3.0000     5.000000   
75%     749.250000    45.000000     2.000000         6.0000     7.000000   
max     999.000000    73.000000     2.000000         8.0000     8.000000   

       Dust Allergy  OccuPational Hazards  Genetic Risk  chronic Lung Disease  \
count   1000.000000           1000.000000   1000.000000           1000.000000   
mean       5.165000              4.840000      4.580000              4.380000   
std        1.980833              2.107805      2.126999              1.848518   
min        1.000000              1.000000      1.000000              1.000000   
25%        4.000000              3.000000      2.000000              3.000000   
50%        6.000000              5.000000      5.000000              4.000000   
75%        7.000000              7.000000      7.000000              6.000000   
max        8.000000              8.000000      7.000000              7.000000   

       Balanced Diet  ...      Fatigue  Weight Loss  Shortness of Breath  \
count    1000.000000  ...  1000.000000  1000.000000          1000.000000   
mean        4.491000  ...     3.856000     3.855000             4.240000   
std         2.135528  ...     2.244616     2.206546             2.285087   
min         1.000000  ...     1.000000     1.000000             1.000000   
25%         2.000000  ...     2.000000     2.000000             2.000000   
50%         4.000000  ...     3.000000     3.000000             4.000000   
75%         7.000000  ...     5.000000     6.000000             6.000000   
max         7.000000  ...     9.000000     8.000000             9.000000   

          Wheezing  Swallowing Difficulty  Clubbing of Finger Nails  \
count  1000.000000            1000.000000               1000.000000   
mean      3.777000               3.746000                  3.923000   
std       2.041921               2.270383                  2.388048   
min       1.000000               1.000000                  1.000000   
25%       2.000000               2.000000                  2.000000   
50%       4.000000               4.000000                  4.000000   
75%       5.000000               5.000000                  5.000000   
max       8.000000               8.000000                  9.000000   

       Frequent Cold    Dry Cough      Snoring       Level  
count    1000.000000  1000.000000  1000.000000  1000.00000  
mean        3.536000     3.853000     2.926000     0.96700  
std         1.832502     2.039007     1.474686     0.83463  
min         1.000000     1.000000     1.000000     0.00000  
25%         2.000000     2.000000     2.000000     0.00000  
50%         3.000000     4.000000     3.000000     1.00000  
75%         5.000000     6.000000     4.000000     2.00000  
max         7.000000     7.000000     7.000000     2.00000  

[8 rows x 25 columns]

# CHECKING THE NULL VALUES

In [ ]:
df.isnull().sum()

index                       0
Patient Id                  0
Age                         0
Gender                      0
Air Pollution               0
Alcohol use                 0
Dust Allergy                0
OccuPational Hazards        0
Genetic Risk                0
chronic Lung Disease        0
Balanced Diet               0
Obesity                     0
Smoking                     0
Passive Smoker              0
Chest Pain                  0
Coughing of Blood           0
Fatigue                     0
Weight Loss                 0
Shortness of Breath         0
Wheezing                    0
Swallowing Difficulty       0
Clubbing of Finger Nails    0
Frequent Cold               0
Dry Cough                   0
Snoring                     0
Level                       0
dtype: int64

# PRINTING COLUMN NAMES

In [ ]:
df.columns

Index(['index', 'Patient Id', 'Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'OccuPational Hazards', 'Genetic Risk',
       'chronic Lung Disease', 'Balanced Diet', 'Obesity', 'Smoking',
       'Passive Smoker', 'Chest Pain', 'Coughing of Blood', 'Fatigue',
       'Weight Loss', 'Shortness of Breath', 'Wheezing',
       'Swallowing Difficulty', 'Clubbing of Finger Nails', 'Frequent Cold',
       'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

# CORRELATIONS

In [ ]:
df.drop(['Patient Id','index'],axis=1,inplace=True)

In [ ]:
for i in df.columns:
    print(i,"----------->",df[i].corr(df['Level']))

Age -----------> 0.042631027890148575
Gender -----------> 0.08622153175999814
Air Pollution -----------> -0.5772685504227858
Alcohol use -----------> -0.434071499688227
Dust Allergy -----------> -0.2649263956860389
OccuPational Hazards -----------> -0.3637483628395184
Genetic Risk -----------> -0.42338173516922234
chronic Lung Disease -----------> -0.4324052151200229
Balanced Diet -----------> -0.6187806692224385
Obesity -----------> -0.5619613485337323
Smoking -----------> -0.6110870153963788
Passive Smoker -----------> -0.6384086523310047
Chest Pain -----------> -0.494704311792731
Coughing of Blood -----------> -0.6311184891117185
Fatigue -----------> -0.40327617642975966
Weight Loss -----------> -0.020537468431402015
Shortness of Breath -----------> -0.14017774644391023
Wheezing -----------> 0.16777299710900287
Swallowing Difficulty -----------> -0.012879844499667212
Clubbing of Finger Nails -----------> 0.11674645406161799
Frequent Cold -----------> -0.17167782590596786
Dry Cough -

In [ ]:
len(df.columns)

26

# REMOVING LOW CORRELATED COLUMNS

In [ ]:
df.drop(['Snoring','Swallowing Difficulty','Wheezing','Shortness of Breath','Passive Smoker','OccuPational Hazards'],axis=1,inplace=True)

In [ ]:
df.tail()

Age  Gender  Air Pollution  Alcohol use  Dust Allergy  Genetic Risk  \
995   44       1              6            7             7             7   
996   37       2              6            8             7             7   
997   25       2              4            5             6             5   
998   18       2              6            8             7             7   
999   47       1              6            5             6             5   

     chronic Lung Disease  Balanced Diet  Obesity  Smoking  Chest Pain  \
995                     6              7        7        7           7   
996                     6              7        7        7           7   
997                     4              6        7        2           4   
998                     6              7        7        8           7   
999                     4              6        7        2           4   

     Coughing of Blood  Fatigue  Weight Loss  Clubbing of Finger Nails  \
995                  7        5            3                         2   
996                  7        9            6                         4   
997                  8        8            7                         4   
998                  9        3            2                         2   
999                  8        8            7                         4   

     Frequent Cold  Dry Cough  Level  
995              4          5      0  
996              3          1      0  
997              6          7      0  
998              4          2      0  
999              6          7      0

# IMPORTING REQUIRED MODELS AND METRICS

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Train Test Split
from sklearn.model_selection import train_test_split

# Metrics
from sklearn.metrics import confusion_matrix, accuracy_score

# Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# DIVIDING THE DEPENDENT AND INDEPENDENT VARIABLES

In [ ]:
y = df['Level']
X = df.drop(['Level'],axis = 1)

# DIVIDING THE DATA INTO TRAIN AND TEST

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
lst = [x_train,x_test,y_train,y_test]
for data in lst:
  print("shape","---->",data.shape)

shape ----> (800, 17)
shape ----> (200, 17)
shape ----> (800,)
shape ----> (200,)


# MAKING PIPELINE FOR EVERY MODEL

In [ ]:
mdl_1 = make_pipeline(StandardScaler(), KNeighborsClassifier()) 
mdl_2 = make_pipeline(StandardScaler(), LogisticRegression()) 
mdl_3 = make_pipeline(StandardScaler(), SVC()) 
mdl_4 = make_pipeline(StandardScaler(), DecisionTreeClassifier()) 
mdl_5 = make_pipeline(StandardScaler(), RandomForestClassifier())

# FITTING AND PREDICTING ACCURACY OF MODELS

In [ ]:
mdl_lst = [mdl_1,mdl_2,mdl_3,mdl_4,mdl_5]
accuracy_lst = []
for mdl in mdl_lst:
  i = 1
  mdl.fit(x_train,y_train)
  y_pred = mdl.predict(x_test)
  print("")
  print("******CLASSIFICATION MODEL******")
  i = i+1
  print("")
  print("CONFUSION MATRIX")
  print(confusion_matrix(y_test,y_pred))
  print("")
  print("ACCURACY SCORE")
  print(accuracy_score(y_test,y_pred))
  print("----------------------------")
  accuracy_lst.append(accuracy_score(y_test,y_pred)) 
 


******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[82  0  0]
 [ 0 55  0]
 [ 0  0 63]]

ACCURACY SCORE
1.0
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[82  0  0]
 [ 0 55  0]
 [ 0  1 62]]

ACCURACY SCORE
0.995
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[82  0  0]
 [ 0 55  0]
 [ 0  0 63]]

ACCURACY SCORE
1.0
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[82  0  0]
 [ 0 55  0]
 [ 0  0 63]]

ACCURACY SCORE
1.0
----------------------------

******CLASSIFICATION MODEL******

CONFUSION MATRIX
[[82  0  0]
 [ 0 55  0]
 [ 0  0 63]]

ACCURACY SCORE
1.0
----------------------------


# CHECKING FOR HIGH ACCURACY SCORE AMOUNG THE MODELS

In [ ]:
print(accuracy_lst.index(max(accuracy_lst)))


0


# SAVING THE MODEL IN PICKLE FILE

In [ ]:
import pickle

In [ ]:
filename = 'lung_cancer.pkl'
pickle.dump(mdl_2, open(filename, 'wb'))